export const BASE_URL = process.env.REACT_APP_BACKEND_API;
export const CLIENT_ID = process.env.REACT_APP_PAYPAL_CLIENT_ID;
export const CLOUDINARY_CLOUD_NAME =
  process.env.REACT_APP_CLOUDINARY_CLOUD_NAME;
export const CLOUDINARY_UPLOAD_PRESET =
  process.env.REACT_APP_CLOUDINARY_UPLOAD_PRESET;
